name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@main

      # DEPLOY FRONTEND TO CLOUDFLARE WORKERS
      - name: Install dependencies for frontent build
        run: npm install --prod --pure-lockfile
        working-directory: frontend

      - name: Build site
        run: 'npm run build'
        working-directory: frontend
        env:
          CI: false

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.17.0'
          environment: 'production'
          workingDirectory: frontend
